{% set name = "environs" %}
{% set version = "9.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2eb671afd37e6e9820131b918bbbcaa6658d0fb420ebf35bdfb750ae39c51a66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - marshmallow
    - python-dotenv

test:
  imports:
    - environs

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - mcs07
