{% set name = "environs" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36081033ab34a725c2414f48ee7ec7f7c57e498d8c9255d61fbc7f2d4bf60865

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - marshmallow
    - python-dotenv

test:
  imports:
    - environs

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - mcs07
