{% set name = "environs" %}
{% set version = "11.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e068ae3174cef52ba4b95ead22e639056a02465f616e62323e04ae08e86a75a4
  patches:
    - patches/0001-remove-some-django-_url-test-dependencies.patch

build:
  number: 0
  skip: True  # [py<310 or py>=314]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - marshmallow >=3.13.0
    - python-dotenv

{% set tests_to_skip = "" %}
# Skip django tests
{% set tests_to_skip = tests_to_skip + "TestDjango" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_invalid" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_email_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_invalid" %}
# Skip Windows-specific test that fails due to different file permission handling
{% set tests_to_skip = tests_to_skip + " or test_read_from_file_path_is_unreadable" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - environs
  requires:
    - pip
    - pytest
    # - django is not required because we skip the *_url tests
  commands:
    - pip check
    - pytest -v tests -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  description: |
    environs is a Python library for parsing environment variables. It
    allows you to store configuration separate from your code, as per
    The Twelve-Factor App methodology.
  doc_url: https://github.com/sloria/environs
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - mcs07
