{% set name = "environs" %}
{% set version = "9.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use upstream archive tarball for tests
  url: https://github.com/sloria/environs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1209b11f6ed2fadca24ae65a4d751ff0b4dfef1391acd75587c96b14cab3f3c8
  patches:
    - patches/0001-remove-some-django-_url-test-dependencies.patch

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

{% set tests_to_skip = "not (" %}
{% set tests_to_skip = tests_to_skip + "TestDjango" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_invalid" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_email_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_invalid" %}
{% set tests_to_skip = tests_to_skip + ")" %}

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - marshmallow >=3.0.0
    - python-dotenv

test:
  source_files:
    - tests
  imports:
    - environs
  requires:
    - pip
    - pytest
    - django
  commands:
    - pip check
    - pytest -v tests -k '{{ tests_to_skip }}'

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  description: |
    environs is a Python library for parsing environment variables. It
    allows you to store configuration separate from your code, as per
    The Twelve-Factor App methodology.
  doc_url: https://github.com/sloria/environs
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - mcs07
