{% set name = "environs" %}
{% set version = "14.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7b8f6fcf3301bc674bc9c03e39b5986d116126ffb96764efd34c339ed9464ee
  patches:
    - patches/0001-remove-some-django-_url-test-dependencies.patch

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - marshmallow >=3.18.0
    - python-dotenv
    - typing-extensions # [py<311]

{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + "TestDjango" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_db_url_with_deferred_validation_invalid" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_email_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_missing" %}
{% set tests_to_skip = tests_to_skip + " or test_dj_cache_url_with_deferred_validation_invalid" %}

test:
  source_files:
    - tests
  imports:
    - environs
  requires:
    - pip
    - pytest
    # - django is not required because we skip the *_url tests
  commands:
    - pip check
    - pytest -v tests -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  description: |
    environs is a Python library for parsing environment variables. It
    allows you to store configuration separate from your code, as per
    The Twelve-Factor App methodology.
  doc_url: https://github.com/sloria/environs
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - mcs07
